### ISSUE TITLE
Battery usage

### ISSUE THREAD

**Issue by timklge** [timklge/karoo-tilehunting#36]
It looks like the extension causes a significant increase in battery usage for users.

It's not entirely clear to me what causes this though. It is certainly related to the tile outline drawing, but the tiles are only redrawn when the current tile position changes, which is very infrequent. So it looks like the drawing of the polylines itself is expensive (which is done every frame by the Karoo).

- [ ] Check if the redraw code is run too often
- [ ] Check if battery usage scales with the count of drawn polylines (e. g. by using the "show grid lines" toggle)
- [ ] Check for optimization potential in the line redraw code. The extension already merges together adjacent grid cell lines, but only in straight lines.

**Comment by kLabz** [comment]
If I remember correctly, the updates are very frequent ; I had to reduce that to avoid burning my battery

**Comment by timklge** [comment]
Thanks for the hint. I'll try to obtain a log of a regular ride to see how often it's actually updated. When testing it at home, the update frequency looks correct.

I've taken a look into the git log and on may 8th, I've added some code because I had forgotten to cancel the cluster redraw coroutine when the karoo map closed event is received. This may have let to expensive redraw jobs accumulating during the ride when switching pages etc with versions before 1.1, but should be fixed since then.

**Comment by kLabz** [comment]
From what I recall, the position / distance we get has extreme precision (something like up to the cm), and I had to round it a bit before filtering

Edit: also, this was with older versions (early-ish april)

**Comment by timklge** [comment]
The karoo forum user who had observed high battery usage when running the extension apparently experiences lower usage after the most recent karoo update. I've not done a long outside ride with the newest version, but on a 2 hour indoor ride, battery usage was noticably lower than before; so maybe it wasn't an issue with the current extension version, but there had been a regression in the karoo system which has been fixed now (without them mentioning it in the changelog).

I'll close this issue if I experience no high usage on my next ride.

**Comment by bobiko** [comment]
Is the problem still occurring? I am thinking about installing an add -on in Karoo 3

**Comment by timklge** [comment]
I’ve been using the tilehunting extension on my device during every ride, and I haven’t noticed a significant increase in battery usage. I *think* the issue is no longer occurring, or it might only arise under specific conditions.

**Comment by bobiko** [comment]
OK, I will risk and install a challenge before 250+ km tomorrow ;-)

**Comment by bobiko** [comment]
Ok I'm coming back to you with information that ... the add-on works very stably, I didn't even notice that it was eating up more energy than before without the add-on :) great job. how great it was to ride, seeing that I was conquering new tiles

however, I noticed that the real Bontrager Flare RT light is consuming the Karoo3 battery a lot.

**Comment by timklge** [comment]
Cool, thanks for the info!
